# Generated by Django 2.0.1 on 2018-04-25 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=100, unique=True)),
                ('senha', models.CharField(max_length=255)),
                ('nome', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=100, unique=True)),
                ('celular', models.CharField(max_length=15, unique=True)),
                ('dt_expiracao', models.DateField()),
                ('ra', models.IntegerField()),
                ('foto', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'Aluno',
                'managed': False,
            },
        ),
    ]
